### ISSUE TITLE
Git Clientsの対応

### ISSUE THREAD

**Issue by KashiuchiSotaroSub** [sotarokashiuchi/JointDevelopmentEnviromentLesson#11]
# 課題
- Gitコマンド(CUI)は初心者には難しい
- Gitを使わない理由になってしまう

# 解決策
- Git Clientsに対応する
- https://git-scm.com/downloads/guis
- 上記のサイトが非常に参考になる
- https://qiita.com/yoshi111/items/3a991a58de4f37d73921
- https://zenn.dev/praha/articles/db1c4bcc4ef48c
- VSCodeも便利である

**Comment by sotarokashiuchi** [comment]
# 方針
- VSCodeのGitとGitHubとGit Graphを使用する予定
- GitHub Pull Requests and Issuesは使用しない
  - Gitの機能だけをVSCodeに依存させ、GitHubは依存しないようにする
